Filesystem support
fabricedesre/cc3200-rs pull request #46
Opened 2016-11-22 12:36 UTC by tdz

2016-11-22 18:11 UTC, fabricedesre commented on cc3200-sys/src/simplelink.rs
> +    pub token: u32,
That should be pub token: [u32; 4]

2016-11-22 18:11 UTC, fabricedesre commented on src/simplelink.rs
> +
I'd prefer a more idiomatic wrapper than this one. While we won't be able to have the exact same API, something closer to https://doc.rust-lang.org/std/fs/struct.File.html would be nice.

2016-11-29 13:25 UTC, tdz commented
I updated the API to be like the Rust file API. I also added a simple example.

2016-11-29 17:23 UTC, fabricedesre requested changes
That's looking great, thanks!
One last thing: The standard library implementation of the Read trait at https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs provides interesting default implementations of read_to_end and read_to_string (see https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L313 and https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L344)

2016-11-29 17:23 UTC, fabricedesre commented on cc3200-sys/src/simplelink.rs
> +    pub flags: u16,
Could that be a repr(u16) Rust enum instead?

2016-11-29 17:23 UTC, fabricedesre commented on examples/fileio.rs
> +}
Not needed in that example

2016-11-29 17:23 UTC, fabricedesre commented on src/simplelink.rs
> +    pub fn remove(file_name: &str) {
that should return a Result<(), SimpleLinkError>

2016-11-29 17:23 UTC, fabricedesre commented on src/simplelink.rs
> +    }
since sync_all and sync_data are no ops, why provide them at all?

2016-11-29 17:23 UTC, fabricedesre commented on src/simplelink.rs
> +        return mode;
nit: s/return mode;/mode

2016-11-29 17:23 UTC, fabricedesre commented on src/simplelink.rs
> +    fn open_with_mode(file_name: &str, mode: u32) -> Result<File, SimpleLinkError> {
I'd prefer the mode to be a rust enum.

2016-11-30 11:34 UTC, tdz commented on cc3200-sys/src/simplelink.rs
> +    pub flags: u16,
That's a bitmap. An enum is probably not the right type here. I guess, I should add an enum containing all the flags.

2016-11-30 11:35 UTC, tdz commented on src/simplelink.rs
> +    pub fn remove(file_name: &str) {
Ok, sure. I thought that an error might not be of interest to the caller, but adding a result doesn't hurt either.

2016-11-30 11:36 UTC, tdz commented on src/simplelink.rs
> +    }
Completeness.

2016-11-30 11:41 UTC, tdz commented on src/simplelink.rs
> +    fn open_with_mode(file_name: &str, mode: u32) -> Result<File, SimpleLinkError> {
'mode' is actually a combination of access mode, a new file's length, and some other flags. [1] An enum really doesn't do here. I used the name 'mode' because that's what the C interface calls it. I wouldn't mind using a better name, if you have one.

[1] https://github.com/fabricedesre/cc3200-rs/blob/master/cc3200-sys/sdk/simplelink/include/fs.h#L145

2016-11-30 12:39 UTC, tdz commented
Should the high-level API be located in cc3200::io rather than c3200::simplelink?

2016-11-30 13:02 UTC, tdz commented on cc3200-sys/src/simplelink.rs
> +    pub flags: u16,
Hmm, but I can't find any documentation about what these flags are.

2016-11-30 14:55 UTC, tdz commented
I pushed an update with the requested small fixes and cleanups. The Read::read_to_end method now work without the additional intermediate copy; it resizes the read buffer in a way similar to the read methods in std::io. The remove function now returns errors.

2016-11-30 16:26 UTC, fabricedesre commented on src/simplelink.rs
> +    }
I get that, but I'm not a fan of making it look like something important is implemented while it's not.

2016-11-30 16:26 UTC, fabricedesre commented on cc3200-sys/src/simplelink.rs
> +    pub flags: u16,
Ok, if you can't find docs, let's keep it like that. If we had doc, we could have used https://doc.rust-lang.org/bitflags/bitflags/macro.bitflags.html

2016-11-30 16:30 UTC, fabricedesre commented
I agree with moving that to cc3200::io

2016-11-30 16:30 UTC, fabricedesre approved these changes

2016-12-01 10:00 UTC, tdz commented
I pushed an update with the code now being located in cc3200:io and the no-op flush() and sync() methods being removed.

2016-12-01 10:40 UTC, merged