SFLASH support and offline updater
fabricedesre/cc3200-rs pull request #60
Opened 2016-12-08 14:47 UTC by tdz

2016-12-08 14:49 UTC, tdz commented
FYI: For testing, I copied the blinky example to /update/mcuimg.bin. After flashing and running the updater application, the device executes blinky.

2016-12-13 14:55 UTC, tdz commented
@fabricedesre  Just friendly ping for a review of this PR.

2016-12-13 15:12 UTC, tdz commented
Updated the PR
 * Added Image::update() for selecting the image's file name automatically
 * Removed 'failsafe' parameter from Image::create(): it's not supported by the SDK

2016-12-13 18:06 UTC, fabricedesre requested changes
Mostly cosmetic changes, and I need to try it locally.

2016-12-13 18:06 UTC, fabricedesre commented on src/io.rs
> +        let len = try!(self.read_to_end(&mut buf));
nit (here and other places): I think you can use let len = self.read_to_end(&mut buf)?;

2016-12-13 18:06 UTC, fabricedesre commented on src/io.rs
> +//
Can we move all this code in it's own file?

2016-12-13 18:06 UTC, fabricedesre commented on src/io.rs
> +    file_handle: i32,
for a followup: we should consider not using i32 for the type here.

2016-12-13 18:06 UTC, fabricedesre commented on src/io.rs
> +        Image::create(next_image_name, max_len)
No need to declare a static str here: Image::create("/sys/mcuImgA.bin", max_len)

2016-12-13 18:06 UTC, fabricedesre commented on examples/update.rs
> +
is that happening when doing File::get_info(filename) ?

2016-12-14 09:51 UTC, tdz commented on src/io.rs
> +//
Image belongs into the io namespace. Can namespaces be split up into multiple files (e.g., io_traits.rs, io_file.rs, io_image.rs)?

2016-12-14 09:52 UTC, tdz commented on src/io.rs
> +    file_handle: i32,
Why? This is the type that the underlying C implementation uses.

2016-12-14 09:53 UTC, tdz commented on src/io.rs
> +        Image::create(next_image_name, max_len)
It's for that comment next to the constant.

2016-12-14 09:53 UTC, tdz commented on examples/update.rs
> +
Not sure, but I think so.

2016-12-14 09:55 UTC, tdz commented on src/io.rs
> +        let len = try!(self.read_to_end(&mut buf));
Wouldn't the compiler complain about an unused Result<>?

2016-12-14 12:43 UTC, tdz commented on src/io.rs
> +        let len = try!(self.read_to_end(&mut buf));
Tried and the compiler stops with an error.

2016-12-14 12:45 UTC, tdz commented on src/io.rs
> +        Image::create(next_image_name, max_len)
I put the comment in front of the create() statement.

2016-12-14 12:55 UTC, tdz commented on src/io.rs
> +//
The interface for testing and committing images is a feature of the boot loader and rather unrelated to reading and writing image files. Therefore I moved these methods from io::Image to cc3200::Update. That should reflect the board-wide nature of these operations.

Being about file access, I still think that Image belongs into io. Internally in the SDK it's mostly the same code as for regular files with some extras for opening. If you really want to see Image being gone, I guess we could merge Image into File without a loss of functionality.

2016-12-14 12:57 UTC, tdz commented
I pushed a new patch set into the PR that updates as explained above.

2016-12-14 15:59 UTC, fabricedesre commented on src/io.rs
> +        let len = try!(self.read_to_end(&mut buf));
Which error? using the `?` operator is very similar to the `try!` macro.

2016-12-14 16:54 UTC, tdz commented on src/io.rs
> +        let len = try!(self.read_to_end(&mut buf));
I see. I thought the question mark was part of the sentence. :)

2016-12-14 16:56 UTC, fabricedesre commented on src/io.rs
> +//
No we can't split namespaces afaik. But I'm fine with having the higher level functions in cc3200::Update

2016-12-14 16:58 UTC, fabricedesre commented on src/io.rs
> +    file_handle: i32,
Sure, but just declaring a type alias like:
```rust
type FileHandle = i32;
```
will hide the implementation details. No big deal anyway.

2017-01-09 12:55 UTC, tdz commented
Updated the PR

  * replaced try! by ?

2017-01-17 12:43 UTC, tdz commented
Updated the PR:

  - fixed string conversion rust<>C, which makes file-name handling reliable
  - removed Image data structure; now implemented as File
  - added examples simple-ota, full-ota, and full-ota-mcuimga that demonstrate OTA mechanisms

2017-01-17 13:51 UTC, tdz commented on examples/update.rs
> +
This has been fixed in the latest PR.

2017-01-18 10:46 UTC, tdz commented
@dhylands Dave, can you continue with the review of this patch set? I'd like to get it merged ASAP.

2017-01-19 04:52 UTC, fabricedesre approved these changes

2017-01-19 04:52 UTC, fabricedesre commented on examples/full-ota.rs
> +    };
that could be:
```rust
if let Err(err) = get_update(...) {
    ignore!(File::remove(...));
    return Err(err);
}

(same change can be done in other examples)

2017-01-19 04:52 UTC, fabricedesre commented on examples/simple-ota.rs
> +    })
maybe the match can be simplified to:
```rust
match $e {
    _ => { },
}
```

2017-01-24 12:11 UTC, tdz commented
Updated PR with the suggested changes.

2017-01-24 12:56 UTC, merged